import { suma } from "./utils/suma.js";
import chalk from "chalk";

function describe(nombreSuite, callback) {
  let total = 0;
  let exitos = 0;

  console.log(chalk.blueBright(`\nüß™ Test Suite: ${nombreSuite}`));
  console.time("‚è± Duraci√≥n");

  const it = (descripcion, fn) => {
    total++;
    try {
      fn();
      exitos++
      console.log(`${chalk.green("‚úì")} ${descripcion}`);
    } catch (error) {
      console.log(`${chalk.red("‚úó")} ${descripcion}`);
      console.log(chalk.red(`   ‚Üí ${error.message}`));
    }
  };
  callback(it);
  console.timeEnd("‚è± Duraci√≥n");
  console.log(
    chalk.bold(`\nResumen:`),
    chalk.green(`${exitos} exitosas`),
    "|",
    chalk.red(`${total - exitos} fallidas`)
  );
}

describe("Pruebas para la funci√≥n suma()", (it) => {
  it("debe retornar 7 en base a la suma de los n√∫meros 4 y 3", () => {
    //* Esta es la fn que le pasamos por callback a la function real it
    const resultado = suma(4, 3);
    const esperado = 7;
    if (resultado !== esperado)
      throw new Error(`Esperado ${esperado}, pero se obtuvo ${resultado}`);
  });
  it("debe retornar 'error' si alg√∫n argumento no es un n√∫mero", () => {
    const resultado = suma(4, "juan");
    const esperado = "error";
    if (resultado !== esperado)
      throw new Error(`Esperado '${esperado}', pero se obtuvo '${resultado}'`);
  });
  it("debe retornar la suma de m√∫ltiples n√∫meros", () => {
    const resultado = suma(1, 2, 3, 4, 5);
    const esperado = 15;
    if (resultado !== esperado)
      throw new Error(`Esperado ${esperado}, pero se obtuvo ${resultado}`);
  });
});
//-------------------------------------------------------------
function describeTest(description, expect, fn) {
  //! **Aqu√≠ CODE**
  //* **Aqu√≠ CODE**
}

// Ejemplo de function callback
//! **Aqu√≠ CODE**
//* **Aqu√≠ CODE**

/*
JEST 

jest.describe (---serie de test---)
jest.it(---es un test TDD en s√≠---)

*/
